apiVersion: apps/v1
kind: Deployment
metadata:
  name: imo-audio-consumer-__CI_PIPELINE_ID__
  namespace: imo
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 16
  selector:
    matchLabels:
      app: imo-audio-consumer
  template:
    metadata:
      labels:
        app: imo-audio-consumer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: audio
                 operator: In
                 values:
                 - "true"
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 18       # Required
            memory: 32Gi # Required
          requests:
            cpu: 12
            memory: 16Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-usercode_in_pthread=true"
        - "-connect_timeout_as_unreachable=20"
        - "-health_check_interval=1"
        - "-config_file=/app/runtime/imo-audio.conf"

        livenessProbe:
          httpGet: 
            path: /
            port: 8000                                           # Required
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000                                            # Required
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/runtime
      terminationGracePeriodSeconds: 3
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp
      - name: config
        configMap:
          name:  imo-audio-consumer-__CI_PIPELINE_ID__
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: imo-audio-consumer
  name: imo-audio-consumer
  namespace: imo
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: imo-audio-consumer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: imo-audio-consumer
    release: pga
  name: imo-audio-consumer
  namespace: imo
spec:
  endpoints:
  - interval: 5s
    path: /brpc_metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node
      replacement: $1
      action: replace

  jobLabel: imo-audio-consumer
  namespaceSelector:
    matchNames:
    - imo 
  selector:
    matchLabels:
      app: imo-audio-consumer
