apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcc-bigolive-avatar-dev
  namespace: bigolive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcc-bigolive-avatar-dev
  template:
    metadata:
      labels:
        app: kcc-bigolive-avatar-dev
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: bigolive-cv
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service-type
                operator: In
                values:
                - kafka-consumer-cpp
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 4
            memory: 32Gi
          requests:
            cpu: 1
            memory: 4Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-port=80"
        - "-log_response_body=true"
        - "-usercode_in_pthread=true"
        - "-connect_timeout_as_unreachable=99"
        - "-health_check_interval=1"
        - "-defer_close_second=10"
        - "-config_file=/app/runtime/bigolive-avatar-dev.conf"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: localtime
          mountPath: /etc/localtime
        - name: corefiles
          mountPath: /data/corefiles
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/runtime

      terminationGracePeriodSeconds: 3
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: corefiles
        hostPath:
          path: /data/corefiles
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp
      - name: config
        configMap:
          name: kcc-bigolive-avatar-dev

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kcc-bigolive-avatar-dev
  name: kcc-bigolive-avatar-dev
  namespace: bigolive
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: kcc-bigolive-avatar-dev

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kcc-bigolive-avatar-dev
    release: pga
  name: kcc-bigolive-avatar-dev
  namespace: bigolive
spec:
  endpoints:
  - interval: 30s
    path: /brpc_metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node
      replacement: $1
      action: replace

  jobLabel: kcc-bigolive-avatar-dev
  namespaceSelector:
    matchNames:
    - bigolive
  selector:
    matchLabels:
      app: kcc-bigolive-avatar-dev
