apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-img-sim-audit
  namespace: ann
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-img-sim-audit
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
