apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiki-video-consumer
  namespace: like
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tiki-video-consumer
  template:
    metadata:
      labels:
        app: tiki-video-consumer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 16 # Required
            memory: 40Gi # Required
          requests:
            cpu: 8
            memory: 32Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-usercode_in_pthread=true"
        - "-connect_timeout_as_unreachable=20"
        - "-health_check_interval=1"
        - "-config_file=/app/runtime/tiki-video.conf"

        livenessProbe:
          httpGet: 
            path: /
            port: 8000                                           # Required
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000                                            # Required
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/runtime
      terminationGracePeriodSeconds: 3
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp
      - name: config
        configMap:
          name: tiki-video-consumer



---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiki-video-consumer
  name: tiki-video-consumer
  namespace: like
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: tiki-video-consumer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tiki-video-consumer
    release: pga
  name: tiki-video-consumer
  namespace: like
spec:
  endpoints:
  - interval: 5s
    path: /brpc_metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node
      replacement: $1
      action: replace

  jobLabel: tiki-video-consumer
  namespaceSelector:
    matchNames:
    - like
  selector:
    matchLabels:
      app: tiki-video-consumer