apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludo-voice-room-cover-consumer
  namespace: ludo
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ludo-voice-room-cover-consumer
  template:
    metadata:
      labels:
        app: ludo-voice-room-cover-consumer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: imo-cv
                 operator: In
                 values:
                 - "true"
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 4
            memory: 32Gi
          requests:
            cpu: 1
            memory: 4Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-port=80"
        - "-usercode_in_pthread=true"
        - "-connect_timeout_as_unreachable=20"
        - "-health_check_interval=1"
        - "-config_file=/app/runtime/ludo-voice-room-cover.conf"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: localtime
          mountPath: /etc/localtime
        - name: corefiles
          mountPath: /data/corefiles
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/runtime

      terminationGracePeriodSeconds: 3
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: corefiles
        hostPath:
          path: /data/corefiles
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp

      - name: config
        configMap:
          name: ludo-voice-room-cover-consumer
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ludo-voice-room-cover-consumer
  name: ludo-voice-room-cover-consumer
  namespace: ludo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: ludo-voice-room-cover-consumer

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ludo-voice-room-cover-consumer
    release: pga
  name: ludo-voice-room-cover-consumer
  namespace: ludo
spec:
  endpoints:
  - interval: 30s
    path: /brpc_metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node
      replacement: $1
      action: replace

  jobLabel: ludo-voice-room-cover-consumer
  namespaceSelector:
    matchNames:
    - ludo
  selector:
    matchLabels:
      app: ludo-voice-room-cover-consumer
