apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcc-ludo-avatar-consumer-dev
  namespace: grey
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcc-ludo-avatar-consumer-dev
  template:
    metadata:
      labels:
        app: kcc-ludo-avatar-consumer-dev
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: imo-cv
                 operator: In
                 values:
                 - "true"
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 4
            memory: 32Gi
          requests:
            cpu: 1
            memory: 4Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-port=80"
        - "-connect_timeout_as_unreachable=20"
        - "-health_check_interval=1"
        - "-defer_close_second=10"
        - "-config_file=/app/runtime/ludo-avatar-dev.conf"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: localtime
          mountPath: /etc/localtime
        - name: corefiles
          mountPath: /data/corefiles
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp

        - name: config
          mountPath: /app/runtime

      terminationGracePeriodSeconds: 3
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: corefiles
        hostPath:
          path: /data/corefiles
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp

      - name: config
        configMap:
          name: kcc-ludo-avatar-consumer-dev
