apiVersion: apps/v1
kind: Deployment
metadata:
  name: stalar-consumer
  namespace: stalar
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stalar-consumer
  template:
    metadata:
      labels:
        app: stalar-consumer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: imo-cv
                 operator: In
                 values:
                 - "true"
      restartPolicy: Always
      imagePullSecrets:
      - name: harbor
      terminationGracePeriodSeconds: 3
      containers:
      - name: consumer
        resources:
          limits:
            cpu: 4                                             # Required
            memory: 12Gi # Required
          requests:
            cpu: 1
            memory: 8Gi
        imagePullPolicy: Always
        image: __IMAGE__
        command:
        - "./kafka-consumer-cpp"
        - "-usercode_in_pthread=true"
        - "-connect_timeout_as_unreachable=20"
        - "-health_check_interval=1"
        - "-config_file=/app/runtime/stalar.conf"

        livenessProbe:
          httpGet:
            path: /
            port: 8000                                           # Required
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000                                            # Required
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:     #挂载volumes中定义的磁盘
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/runtime

      terminationGracePeriodSeconds: 3
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: tmp
        hostPath:
          path: /tmp
      - name: config
        configMap:
          name: stalar-consumer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stalar-consumer
  name: stalar-consumer
  namespace: stalar 
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: stalar-consumer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: stalar-consumer
    release: pga
  name: stalar-consumer
  namespace: stalar
spec:
  endpoints:
  - interval: 5s
    path: /brpc_metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node
      replacement: $1
      action: replace

  jobLabel: stalar-consumer
  namespaceSelector:
    matchNames:
    - stalar
  selector:
    matchLabels:
      app: stalar-consumer
